const TOOL_DATA={
 states:{
  LA:{name:'Louisiana',summary:'Near-term strategy: MCO-funded pilot, care-management/quality budget, or risk-bearing provider partnership. A broad statewide Medicaid nutrition authority is not confirmed.',defaultMealCost:7.92,cohorts:{
   complex:{affected:4500,annualCost:55092,targetRate:100,note:'Recommended proof cohort: medically and socially complex adults with recent acute utilization, diet-sensitive illness and inability to obtain or prepare appropriate food.',buyer:'Which members had a recent hospitalization, annualized spending near or above $50,000, a diet-sensitive condition and a documented nutrition barrier?',cost:'High baseline claims and inpatient risk create enough avoidable spending for a short pilot.',fit:'Strongest evidence fit; clinician certification and payer claims are required.'},
   diabetes:{affected:480000,annualCost:12022,targetRate:6,note:'Screening population only. Diabetes diagnosis alone is too broad for an ROI pilot.',buyer:'Which diabetic members also have recent avoidable utilization and food barriers?',cost:'Large population but cost is diffuse unless acuity filters are added.',fit:'Good clinical fit after adding high-risk criteria.'},
   heart:{affected:90000,annualCost:24000,targetRate:12,note:'Use heart failure with a recent admission/readmission and food-access barrier.',buyer:'Which heart-failure members have recent inpatient use and difficulty following a sodium-controlled diet?',cost:'Admissions and readmissions concentrate cost.',fit:'Strong disease filter when combined with recent utilization.'},
   ckd:{affected:490000,annualCost:18000,targetRate:5,note:'Use stage 3b–4 CKD with rising utilization and renal-specific oversight.',buyer:'Which pre-dialysis CKD members have nutrition insecurity and rising utilization?',cost:'Progression and comorbidity create downstream cost.',fit:'Potentially strong but clinically specialized.'}},
   funding:[
    {name:'MCO innovation or controlled pilot budget',status:'Conditional',score:95,desc:'Plan-funded test with a defined cohort, capped budget and agreed evaluation.',buyer:'Plan president, CMO, care management, health equity or innovation',need:'Budget owner, claims-defined cohort, implementation plan and stop/scale criteria.'},
    {name:'Care-management, quality or health-equity budget',status:'Conditional',score:88,desc:'Nutrition intervention tied to a quality, disparity or utilization objective.',buyer:'CMO, quality, population health, care management or health equity',need:'Quality gap, clinical referral and measurement plan.'},
    {name:'Risk-bearing provider / value-based partnership',status:'Conditional',score:84,desc:'Provider funds the intervention against shared-savings or avoidable-utilization goals.',buyer:'CFO, value-based care or population health executive',need:'Attributed population, risk contract and baseline utilization.'},
    {name:'Section 1115 / HRSN / in-lieu-of-services policy route',status:'Verify',score:52,desc:'Longer-term state and federal authority pathway.',buyer:'Louisiana Medicaid policy and managed-care contracting',need:'Legal authority, service definition, rates and evaluation.'},
    {name:'Grant or community-benefit bridge',status:'Conditional',score:68,desc:'Time-limited capital while payer authority develops.',buyer:'Health-system community benefit, foundations or public health',need:'Transition plan and payer-relevant outcomes.'}]},
  NC:{name:'North Carolina',summary:'Healthy Opportunities Pilots provide a tested HRSN architecture and published fee schedule; verify current funding and operating status before presenting it as available revenue.',defaultMealCost:7.92,cohorts:{
   complex:{affected:4500,annualCost:55092,targetRate:100,note:'Demonstration estimate; replace with plan claims.',buyer:'Which medically and socially complex members meet clinical and social-risk criteria?',cost:'High baseline utilization and acute risk.',fit:'Strongest evidence fit.'},
   diabetes:{affected:1080000,annualCost:12022,targetRate:6,note:'Broad screening cohort only.',buyer:'Which diabetic members meet social-risk and utilization criteria?',cost:'Large prevalence, diffuse cost.',fit:'Needs high-acuity filter.'},
   heart:{affected:215000,annualCost:24000,targetRate:12,note:'Use recent admission/readmission.',buyer:'Which heart-failure members have qualifying social risk?',cost:'Concentrated inpatient spending.',fit:'Strong disease filter.'},
   ckd:{affected:1190000,annualCost:18000,targetRate:5,note:'Do not add overlapping cohorts.',buyer:'Which pre-dialysis CKD members have social risk?',cost:'Progression and comorbidity.',fit:'Requires renal oversight.'}},funding:[
    {name:'Healthy Opportunities Pilots / Section 1115 route',status:'Verify current status',score:72,desc:'Food, housing, transportation and safety services through a formal HRSN model.',buyer:'NC Medicaid, plans, network leads and HSOs',need:'Current funding, eligibility, authorization and contracting.'},
    {name:'Plan-funded innovation pilot',status:'Conditional',score:90,desc:'Plan-funded test using HOP evidence and infrastructure lessons.',buyer:'Plan CMO, quality, care management or innovation',need:'Authority, cohort, procurement and evaluation.'},
    {name:'Risk-bearing provider partnership',status:'Conditional',score:84,desc:'Accountable provider funds against avoidable utilization.',buyer:'Health-system population health or VBC leader',need:'Attributed lives and financial risk.'}]}
 },
 cohorts:{complex:'High-acuity medically + socially complex (recommended)',diabetes:'Type 2 diabetes + food-access barrier',heart:'Heart failure / cardiovascular high-risk',ckd:'Pre-dialysis chronic kidney disease'},
 savings:{
  complex:{low:630,base:1103,high:1575,basis:'JAMA matched-cohort implied gross medical reductions. Published net difference including an approximately $350 PMPM program cost was $753 PMPM; observational, not guaranteed.'},
  diabetes:{low:20,base:40,high:70,basis:'Conservative planning assumptions; broad diabetes alone is not the recommended ROI cohort.'},
  heart:{low:160,base:280,high:440,basis:'Planning range for post-discharge/high-utilization heart failure; replace with plan claims.'},
  ckd:{low:45,base:105,high:180,basis:'Planning range for high-risk pre-dialysis CKD; replace with claims and renal clinical review.'}},
 companies:{LA:[
  {id:'aetna',name:'Aetna Better Health of Louisiana',contacts:[['Aetna President — corporate context','Steve Nelson','Publicly verified'],['Louisiana plan president / market CEO','Public name not verified','Research required'],['Louisiana chief medical officer','Public name not verified','Research required'],['Provider experience / network route','Aetna Better Health of Louisiana Provider Experience','Public plan team']]},
  {id:'ameri',name:'AmeriHealth Caritas Louisiana',contacts:[['Corporate president / CEO context','Kelly A. Munson','Verify current title'],['Louisiana plan president / market CEO','Public name not verified','Research required'],['Louisiana chief medical officer','Public name not verified','Research required'],['Provider network / contracting route','AmeriHealth Caritas Louisiana Provider Services','Public plan team']]},
  {id:'healthyblue',name:'Healthy Blue Louisiana',contacts:[['Elevance Health CEO — corporate context','Gail K. Boudreaux','Publicly verified'],['Louisiana market president / CEO','Public name not verified','Research required'],['Louisiana chief medical officer','Public name not verified','Research required'],['Provider relations route','Healthy Blue Louisiana Provider Relations','Public plan team']]},
  {id:'humana',name:'Humana Healthy Horizons Louisiana',contacts:[['Humana President & CEO — corporate context','Jim Rechtin','Publicly verified'],['Louisiana market president / CEO','Public name not verified','Research required'],['Louisiana Medicaid chief medical officer','Public name not verified','Research required'],['Provider contracting route','Humana Healthy Horizons Louisiana Provider Relations','Public plan team']]},
  {id:'lhcc',name:'Louisiana Healthcare Connections',contacts:[['Centene CEO — corporate context','Sarah London','Publicly verified'],['Louisiana plan president / CEO','Public name not verified','Research required'],['Louisiana chief medical officer','Public name not verified','Research required'],['Provider relations route','Louisiana Healthcare Connections Provider Services','Public plan team']]},
  {id:'uhc',name:'UnitedHealthcare Community Plan Louisiana',contacts:[['UnitedHealthcare CEO — corporate context','Tim Noel','Publicly verified'],['Louisiana Community Plan president / CEO','Public name not verified','Research required'],['Louisiana Community Plan chief medical officer','Public name not verified','Research required'],['Provider relations route','UnitedHealthcare Community Plan Louisiana Provider Relations','Public plan team']]},
  {id:'ldh',name:'Louisiana Medicaid / LDH',contacts:[['LDH secretary / executive leadership','Verify current officeholder','Immediate verification required'],['Louisiana Medicaid executive director','Public name not verified','Research required'],['Managed-care contracting leader','Public name not verified','Research required'],['HRSN / health-equity policy lead','Public name not verified','Research required']]}
 ],NC:[{id:'ncmedicaid',name:'NC Medicaid / NCDHHS',contacts:[['Medicaid executive leadership','Verify current officeholder','Research required'],['Healthy Opportunities leadership','Verify current officeholder','Research required']]}]},
 sdoh:{
  Food:{'Why does SDOH matter for high-acuity members?':{answer:'Because medical acuity identifies who is expensive, while SDOH identifies why the treatment plan may fail outside the clinic. A high-risk member who cannot buy, store, prepare or receive the prescribed food may remain unstable even with excellent medical care.',owner:'Clinical lead + care management + member operations',need:['Clinical risk','Food access/preparation barrier','Delivery/storage readiness','Member consent'],next:'Use both medical risk and a specific modifiable social barrier as eligibility gates.'},'Is a meal program the right intervention?':{answer:'Only when inability to obtain or prepare clinically appropriate food is a material reason the care plan is failing.',owner:'Clinical lead + care management',need:['Clinical condition','Food barrier','Member preference','Alternative services considered'],next:'Choose the least intensive service that solves the barrier.'}},
  Housing:{'Can meals work with unstable housing?':{answer:'Not reliably without a safe delivery point, refrigeration and storage. Housing support or an alternate delivery model may be required.',owner:'Care management + housing + operations',need:['Stable location','Storage','Contact plan'],next:'Add housing-readiness to onboarding.'}},
  Transportation:{'When is delivery better than transportation?':{answer:'Delivery is better when transportation prevents food access and the member can safely receive meals. Transportation may be better when shopping and cooking are otherwise feasible.',owner:'Care management + logistics',need:['Transport barrier','Delivery coverage','Cooking ability'],next:'Compare alternatives.'}}
 },
 opportunity:[['Funding authority and budget owner',18],['Targetable cohort and claims burden',16],['Economic buyer access',13],['Clinical champion and referral workflow',12],['Delivery and member operations readiness',10],['Data access and evaluation design',13],['Procurement and contracting clarity',10],['Evidence-to-account fit',8]],
 sources:[
  ['Berkowitz et al., JAMA Internal Medicine','10 meals/week; matched cohort; $350 PMPM program cost; $4,591 untreated PMPM; $3,838 treated total PMPM; $753 net difference','2019','Moderate-High','Retrospective observational study, not randomized or Louisiana-specific','https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2730768'],
  ['NCDHHS Healthy Opportunities evaluation','$164 PMPM average net Medicaid savings across HRSN domains','2026','High for reported preliminary result','Not food-only','https://www.ncdhhs.gov/news/press-releases/2026/06/02/healthy-opportunities-pilots-lead-healthier-outcomes-and-reduce-nc-medicaid-costs'],
  ['NC HOP fee schedule','$7.92 medically tailored home-delivered meal','2024','High','Historical public fee, not CookUnity pricing','https://www.ncdhhs.gov/healthy-opportunities-pilot-fee-schedule-and-service-definitions/open'],
  ['Louisiana enrollment context','Approximately 1.4–1.5 million Medicaid enrollees used as editable planning base','2025–2026','Moderate','Refresh from current CMS/LDH data','https://ldh.la.gov/page/medicaid']]
};